volumes:
  db_data:
  storage:

services:
  app:
    container_name: snipeit-app
    image: snipe/snipe-it:v8.3.7
    restart: unless-stopped
    #user: www-data
    #user: ubuntu
    #user: "docker:root"
    networks:
      - frontend
      - backend
    volumes:
      - storage:/var/lib/snipeit
    ports:
      - "${APP_PORT:-8000}:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
  db:
    container_name: snipeit-db
    image: mariadb:lts
    restart: unless-stopped
    user: mysql
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

# https://docs.docker.com/compose/how-tos/networking/
networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend:
    internal: true
